### ISSUE TITLE
master branch is not compiling

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-kallax#46] opened 2017-01-26 13:59 UTC
Trace:

```
14:58 $ go build ./...
# github.com/src-d/go-kallax/tests
tests/kallax.go:264: embedded type cannot be a pointer to interface
tests/kallax.go:600: embedded type cannot be a pointer to interface
tests/kallax.go:936: embedded type cannot be a pointer to interface
tests/kallax.go:1264: embedded type cannot be a pointer to interface
tests/kallax.go:1592: embedded type cannot be a pointer to interface
tests/kallax.go:1920: embedded type cannot be a pointer to interface
tests/kallax.go:2282: embedded type cannot be a pointer to interface
tests/kallax.go:2610: embedded type cannot be a pointer to interface
tests/kallax.go:2938: embedded type cannot be a pointer to interface
tests/kallax.go:3270: embedded type cannot be a pointer to interface
tests/kallax.go:3270: too many errors
```

**Comment by dpordomingo** [comment] 2017-01-27 10:28
@ajnavarro I can not reproduce this bug with the last version of available code at https://github.com/src-d/go-kallax/pull/50

**Comment by erizocosmico** [comment] 2017-01-30 14:02
Yep, we know, will be fixed as soon as we can.

**Comment by erizocosmico** [comment] 2017-01-30 14:07
Seems to be compiling right now. Closing.

**Closed by erizocosmico** 2017-01-30 14:07 UTC
Labels: bug
