### ISSUE TITLE
Debug() gets lost when saving with relations due to transactions.

### ISSUE THREAD

**Issue by nawuko** [src-d/go-kallax#254] opened 2018-01-19 05:10 UTC
If we currently create a new store with .Debug() we don't get any output when saving schemas with relations since transactions take place in a newly constructed store that no longer inherits our debug proxy. 

Following does occur [user.Save](https://github.com/src-d/go-kallax/blob/master/generator/templates/model.tgo#L349) -> [user.Insert](https://github.com/src-d/go-kallax/blob/master/generator/templates/model.tgo#L169) -> [Store.Transaction()](https://github.com/src-d/go-kallax/blob/master/store.go#L425) -> [newStoreWithTransaction](https://github.com/src-d/go-kallax/blob/master/store.go#L112) [at this point our debug proxy gets lost]

If i'm not mistaken its currently not possible to have .Debug() logs for anything that happens during a [Store.Transaction](https://github.com/src-d/go-kallax/blob/master/store.go#L425)

--
Sorry for my broken english, if you have problems to understand the issue due to the poor description feel free to ask any questions.

**Comment by roobre** [comment] 2018-01-19 22:31
When a new store is created with `newStoreWithTransaction`, it doesn't inherit the previous store proxies, so it the debug is effectively lost.

I can confirm this as unintended behaviour. Should be easy to fix, expect it to arrive in a few days (I'm currently a bit busy).

**Comment by nawuko** [comment] 2018-01-19 22:39
Awesome, thank you for looking into the issue and sorry again for being a bit unclear in the issue description.

**Comment by roobre** [comment] 2018-01-19 22:44
No problem at all!

As a workaround, try to re-obtain a debugging instance inside of the transaction callback function:

```go
store.Transaction(func(s *UserStore) error {
        s = s.Debug() // Re-obtain debug-enabled store
        if err := s.Insert(user1); err != nil {
                return err
        }

        return s.Insert(user2)
})
```

Please tell me if this works for you.

**Comment by roobre** [comment] 2018-01-22 19:23
Ideally `.Debug()` is only for, well, debug purposes. Kallax should be assumed to generate valid SQL, so it's there to help with type translations, scans, and other *delicate* parts of row mapping.

Anyway, I'll write a fix for this, since it's certainly intuitive that transactions issued on a debug store are debugged as well.

**Comment by roobre** [comment] 2018-01-29 16:27
Fixed. This will close automatically when I merge the changes into `master`.

**Closed** 2018-01-29 17:29 UTC
Labels: area/kallax, bug

**Comment by nawuko** [comment] 2018-01-29 20:11
Awesome, thank you 👍
