### ISSUE TITLE
"Plugins" api

### ISSUE THREAD

**Issue by josephbuchma** [src-d/go-kallax#239] opened 2017-09-28 15:18 UTC
I've digged codebase a bit, and I found it really well organized.
While active contribution to some internals still requires further investigation, adding new methods / functions is super easy just by editing templates. So I see a great opportunity here to make kallax extendable, and even almost entirely plugin-based, which will provide following benefits:

- With clear documented plugin API it will be much easier to contribute.
- You don't need to fork project or wait until your PR will be merged.
- You can "compose" your kallax, as much opinionated as you want, by including your opinionated set of opinionated plugins that provide opinionated API with opinionated functionality :)
- You can write your "private" plugins to generate even more "opinionated" code :) Maybe even something application-specific.

The obvious starting point to me is to create api for adding templates.

But it's still "draft" thought. While maintainers are away, what do you think @roobre ?

**Comment by roobre** [comment] 2017-09-28 15:47
Hm, what use cases for plugins would you think of?

Maybe the concept of an ORM is too simple for this. I mean, I can't think of any kind of pluggable behaviour. If it is a feature, it can be merged. If it can't, it's because it would require a big refactor due to how it was designed on the first place.

Could you provide some examples of what you think plugins should do?

**Comment by roobre** [comment] 2017-11-23 12:19
As there are no clear use cases where this functionality could be useful, I'm closing this for now to keep the issues panel clearer.

Feel free to keep commenting on this tho, it will be reopened if the discussion reveals interesting use cases.

**Closed by roobre** 2017-11-23 12:19 UTC
Labels: discussion, low priority
