### ISSUE TITLE
Update() destroys existing second-level relationships

### ISSUE THREAD

**Issue by roobre** [src-d/go-kallax#211] opened 2017-07-28 15:05 UTC
Looks like `Person.Save()` saves only first level relationships, just like the README says. However, second-level relationships are destroyed if they already exist.

The most inmediate fix would be to avoid this behaviour, making `Update()` ignore second-level relationships instead of deleting them.

As, in most cases, one would want to change just the relationship itself and not the whole depending object, a plain `Update()` function may be appreciated.

In fact, I think the case where you want to edit an object and its relatives in the same operation is fairly common for insertions, but relatively rare for updates. So making this new "plain update" the default behaviour and delegating the current "full update" operation to a different method might be worth considering.

**Comment by erizocosmico** [comment] 2017-08-01 07:41
Thanks for reporting this! We'll look into this issue as soon as we can.

Because of the breaking changes, it could not be default behavior until 2.0, but we can add a `UpdateOnly` or something like this.

**Comment by erizocosmico** [comment] 2017-08-01 07:50
**NOTE**: Reproduction case has been merged in `fix/save-relations`. The bug will be fixed in that branch and then PR'd.

**Closed** 2017-08-03 13:36 UTC
Labels: area/kallax, bug
